media:
  input: src/contents/blog
  categories: [image, video]
  output: src/contents/blog
content:
  - name: blog
    path: src/contents/blog
    type: collection
    filename: "{fields.filename}.md"
    view:
      fields: [title, published, date, body]
    fields:
      - name: filename
        label: ファイル名
        type: text
        required: true
      - name: title
        label: タイトル
        type: text
        required: true
      - name: published
        label: 公開設定
        type: boolean
        required: true
      - name: date
        label: 日付
        type: date
        required: true
      - name: body
        label: 本文
        type: rich-text
